var integrantesTodos = [
    {
        id: 0,
        foto: "emiliano.jpeg",
        nombre: "Emiliano",
        apellido: "Brancciari",
        edad: 43,
        rol: "Cantante &#127908;",
        apodo: "Emi",
        nacionalidad: "Argentino",
        cancionpreferida: "No necesito nada",
        hobbies: "Ciclismo y natación",
        signo: "Escorpio"
    },
    {
        id: 1,
        foto: "martin.jpeg",
        nombre: "Martín",
        apellido: "Gil",
        edad: 44,
        rol: "Trompetista &#127930;",
        apodo: "Tincho",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Verte reír",
        hobbies: "Leer novelas",
        signo: "Cáncer"
    },
    {
        id: 2,
        foto: "denis.jpeg",
        nombre: "Denis",
        apellido: "Ramos",
        edad: 39,
        rol: "Trombonista &#129687;",
        apodo: "Danonino",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Chau",
        hobbies: "Jugar al tenis",
        signo: "Libra"
    },
    {
        id: 3,
        foto: "mauricio.jpeg",
        nombre: "Mauricio",
        apellido: "Ortiz",
        edad: 46,
        rol: "Saxofonista &#127927;",
        apodo: "Mauri",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Fuera de control",
        hobbies: "Jardineria",
        signo: "Géminis"
    },
    {
        id: 4,
        foto: "diego.jpeg",
        nombre: "Diego",
        apellido: "Bartaburu",
        edad: 40,
        rol: "Baterista &#129345;",
        apodo: "Diegui",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Padre de la patria",
        hobbies: "Ir al gimnasio",
        signo: "Leo"
    },
    {
        id: 5,
        foto: "guzman.jpeg",
        nombre: "Guzmán",
        apellido: "Silveira",
        edad: 39,
        rol: "Bajista &#127928;",
        apodo: "Diegui",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Vivir muriendo",
        hobbies: "Mirar series",
        signo: "Aries"
    },
    {
        id: 6,
        foto: "pablo.jpeg",
        nombre: "Pablo",
        apellido: "Coniberti",
        edad: 46,
        rol: "Guitarrista &#127928;",
        apodo: "Pablin",
        nacionalidad: "Argentina",
        cancionpreferida: "Al vacío",
        hobbies: "Ir al gimnasio",
        signo: "Piscis"
    },
    {
        id: 7,
        foto: "francisco.jpeg",
        nombre: "Francisco",
        apellido: "Nasser",
        edad: 46,
        rol: "Tecladista &#127929;",
        apodo: "Fran",
        nacionalidad: "Uruguaya",
        cancionpreferida: "Yendo",
        hobbies: "Ir al gimnasio",
        signo: "Escorpio"
    },
]