var shows = [
    {
        id: 0,
        imagen: "mdeo3.jpeg",
        departamento: "Montevideo",
        ubicacion: "Antel Arena",
        fecha: "2021/10/16",
        hora: "21:00",
        precio: 1800,
    },
    {
        id: 1,
        imagen: "mdeo2.jpeg",
        departamento: "Montevideo",
        ubicacion: "Velódromo Municipal",
        fecha: "2021/12/18",
        hora: "20:00",
        precio: 1400,
    },
    {
        id: 2,
        imagen: "salto.jpeg",
        departamento: "Salto",
        ubicacion: "Parque Harriague",
        fecha: "2021/09/05",
        hora: "17:00",
        precio: 1190,
    },
    {
        id: 3,
        imagen: "canelones.jpeg",
        departamento: "Canelones",
        ubicacion: "Teatro Politeama",
        fecha: "2021/10/27",
        hora: "20:00",
        precio: 1000,
    },
    {
        id: 4,
        imagen: "artigas.jpeg",
        departamento: "Artigas",
        ubicacion: "Estadio Matías González",
        fecha: "2021/11/02",
        hora: "20:00",
        precio: 990,
    },
    {
        id: 5,
        imagen: "rocha.jpg",
        departamento: "Rocha",
        ubicacion: "Teatro 25 de Mayo",
        fecha: "2021/06/10",
        hora: "20:00",
        precio: 990,
    },
    {
        id: 6,
        imagen: "paysandu.jpeg",
        departamento: "Paysandú",
        ubicacion: "Teatro Florencio Sánchez",
        fecha: "2021/08/16",
        hora: "20:00",
        precio: 1190,
    },
    {
        id: 7,
        imagen: "rionegro.jpeg",
        departamento: "Río Negro",
        ubicacion: "Cine Teatro Atenas",
        fecha: "2021/10/05",
        hora: "20:00",
        precio: 1200,
    },
    {
        id: 8,
        imagen: "rivera.jpeg",
        departamento: "Rivera",
        ubicacion: "Teatro Municipal",
        fecha: "2021/11/24",
        hora: "20:00",
        precio: 1300,
    },
    {
        id: 9,
        imagen: "tacuarembo.jpeg",
        departamento: "Tacuarembó",
        ubicacion: "Club Tacuarembó",
        fecha: "2021/11/07",
        hora: "20:00",
        precio: 1000,
    },
    {
        id: 10,
        imagen: "durazno.jpeg",
        departamento: "Durazno",
        ubicacion: "Teatro Español",
        fecha: "2021/09/26",
        hora: "19:00",
        precio: 1100,
    },
    {
        id: 11,
        imagen: "cerrolargo.jpeg",
        departamento: "Cerro Largo",
        ubicacion: "Teatro España",
        fecha: "2021/09/22",
        hora: "19:00",
        precio: 1100,
    },
    {
        id: 12,
        imagen: "soriano.jpeg",
        departamento: "Soriano",
        ubicacion: "Teatro 28 de Febrero",
        fecha: "2021/11/08",
        hora: "19:00",
        precio: 1200,
    },
    {
        id: 13,
        imagen: "flores.jpeg",
        departamento: "Flores",
        ubicacion: "Teatro Artigas",
        fecha: "2021/06/10",
        hora: "19:00",
        precio: 1190,
    },
    {
        id: 14,
        imagen: "florida.jpeg",
        departamento: "Florida",
        ubicacion: "Teatro 25 de Agosto",
        fecha: "2021/08/16",
        hora: "19:00",
        precio: 1320,
    },
    {
        id: 15,
        imagen: "treintaytres.jpeg",
        departamento: "Treinta y Tres",
        ubicacion: "Cine Teatro Municipal",
        fecha: "2021/09/24",
        hora: "19:00",
        precio: 1080,
    },
    {
        id: 16,
        imagen: "colonia.jpeg",
        departamento: "Colonia",
        ubicacion: "Cine Helvético",
        fecha: "2021/12/03",
        hora: "19:00",
        precio: 1250,
    },
    {
        id: 16,
        imagen: "lavalleja.jpeg",
        departamento: "Lavalleja",
        ubicacion: "Teatro Lavalleja",
        fecha: "2021/09/28",
        hora: "19:00",
        precio: 1150,
    },
    {
        id: 17,
        imagen: "sanjose.jpeg",
        departamento: "San José",
        ubicacion: "Teatro Macció",
        fecha: "2021/10/16",
        hora: "19:00",
        precio: 1040,
    },
    {
        id: 18,
        imagen: "maldonado.jpeg",
        departamento: "Maldonado",
        ubicacion: "Centro de Convenciones",
        fecha: "2021/09/01",
        hora: "19:00",
        precio: 1500,
    },
    {
        id: 19,
        imagen: "mdeo1.jpeg",
        departamento: "Montevideo",
        ubicacion: "Auditorio Nacional del Sodre",
        fecha: "2021/12/08",
        hora: "19:00",
        precio: 1600,
    },
]